repository: cuijingyu/cuijingyu.github.io
repository_url: https://github.com/cuijingyu/cuijingyu.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: 北邮人导航 · BYR-Navi-测试版title
alias_en: BYR-Navi-测试版alias_en
alias_cn: 北邮人导航-测试版alias_cn
description: A Navigation Website for BYR-测试版description描述
keywords: 北邮人导航, BYR-Navi, BYR, BUPT, Navi, Navigation, 测试版keywords
url: http://navi.haoyouduo.top
established_at: "2020-1-07T00:00+08:00"

author: 作者
author_url: https://cuijingyu.github.io
organization: TEELAB
organization_url: https://cuijingyu.github.io
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor